services:
  app:
    image: docker-nextjs-dev
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./styles:/app/styles
      - ./backend:/app/backend
      - ./public:/app/public
